#!/usr/bin/env python
"""
Autogenerated manage.py by Django

Default DJANGO_SETTINGS_MODULE is configured to be used as local.
To use production settings use --settings=safe.settings.production in manage.py commands
"""

import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "safe.settings.local")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
