<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistIsortLinter' => 'lint/ArcanistIsortLinter.php',
    'DjangoUnitTestEngine' => 'unit/DjangoUnitTestEngine.php',
    'PythonBaseUnitTestEngine' => 'unit/PythonBaseUnitTestEngine.php',
  ),
  'function' => array(
    'microtime_float' => 'unit/PythonBaseUnitTestEngine.php',
  ),
  'xmap' => array(
    'ArcanistIsortLinter' => 'ArcanistExternalLinter',
    'DjangoUnitTestEngine' => 'PythonBaseUnitTestEngine',
    'PythonBaseUnitTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
